export const GET_MERCHANT_PROFILE = 'GET_MERCHANT_PROFILE';
export const GET_MERCHANT_PROFILE_SUCCESS = 'GET_MERCHANT_PROFILE_SUCCESS';
export const GET_MERCHANT_PROFILE_FAILURE = 'GET_MERCHANT_PROFILE_FAILURE';

export const GET_MERCHANT_VENUES = 'GET_MERCHANT_VENUES';
export const GET_MERCHANT_VENUES_SUCCESS = 'GET_MERCHANT_VENUES_SUCCESS';

export const UPDATE_MERCHANT_PROFILE = 'UPDATE_MERCHANT_PROFILE';
export const UPDATE_MERCHANT_PROFILE_SUCCESS = 'UPDATE_MERCHANT_PROFILE_SUCCESS';

export const CREATE_MERCHANT_VENUE = 'CREATE_MERCHANT_VENUE';
export const CREATE_MERCHANT_VENUE_SUCCESS = 'CREATE_MERCHANT_VENUE_SUCCESS';

export const UPDATE_MERCHANT_VENUE = 'UPDATE_MERCHANT_VENUE';
export const UPDATE_MERCHANT_VENUE_SUCCESS = 'UPDATE_MERCHANT_VENUE_SUCCESS';

export const DELETE_MERCHANT_VENUE = 'DELETE_MERCHANT_VENUE';
