export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const VERIFY_EMAIL_USER = 'VERIFY_EMAIL_USER';
export const VERIFY_EMAIL_USER_SUCCESS = 'VERIFY_EMAIL_USER_SUCCESS';

export const VALIDATE_EMAIL_USER = 'VALIDATE_EMAIL_USER';
export const VALIDATE_EMAIL_USER_SUCCESS = 'VALIDATE_EMAIL_USER_SUCCESS';

export const DELETE_EMAIL_VALIDATE_USER = 'DELETE_EMAIL_VALIDATE_USER';
