export const CREATE_MERCHANT = 'CREATE_MERCHANT';

export const LOGIN_MERCHANT = 'LOGIN_MERCHANT';
export const LOGOUT_MERCHANT = 'LOGOUT_MERCHANT';

export const VERIFY_EMAIL_MERCHANT = 'VERIFY_EMAIL_MERCHANT';
export const VERIFY_EMAIL_MERCHANT_SUCCESS = 'VERIFY_EMAIL_MERCHANT_SUCCESS';

export const VALIDATE_EMAIL_MERCHANT = 'VALIDATE_EMAIL_MERCHANT';
export const VALIDATE_EMAIL_MERCHANT_SUCCESS = 'VALIDATE_EMAIL_MERCHANT_SUCCESS';

export const DELETE_EMAIL_VALIDATE_MERCHANT = 'DELETE_EMAIL_VALIDATE_MERCHANT';
