export const UPDATE_FORGOT_PASSWORD_USER = 'UPDATE_FORGOT_PASSWORD_USER';
export const UPDATE_FORGOT_PASSWORD_USER_SUCCESS = 'UPDATE_FORGOT_PASSWORD_USER_SUCCESS';
export const UPDATE_FORGOT_PASSWORD_USER_FAILURE = 'UPDATE_FORGOT_PASSWORD_USER_FAILURE';
