export const GET_MERCHANTS = 'GET_MERCHANTS';
export const SET_MERCHANTS = 'SET_MERCHANTS';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const SET_CATEGORIES = 'SET_CATEGORIES';

export const GET_VENUE_DETAIL = 'GET_VENUE_DETAIL';
export const GET_VENUE_DETAIL_SUCCESS = 'GET_VENUE_DETAIL_SUCCESS';

export const GET_VENUE_SCHEDULE = 'GET_VENUE_SCHEDULE';
export const GET_VENUE_SCHEDULE_SUCCESS = 'GET_VENUE_SCHEDULE_SUCCESS';

export const CREATE_TOKEN_PAYMENT = 'CREATE_TOKEN_PAYMENT';
export const CREATE_TOKEN_PAYMENT_SUCCESS = 'CREATE_TOKEN_PAYMENT_SUCCESS';

export const CREATE_PAYMENT = 'CREATE_PAYMENT';
export const CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS';

export const SEND_EMAIL_PAYMENT = 'SEND_EMAIL_PAYMENT';
