export const FORGOT_PASSWORD_USER = 'FORGOT_PASSWORD_USER';
export const FORGOT_PASSWORD_USER_SUCCESS = 'FORGOT_PASSWORD_USER_SUCCESS';

export const FORGOT_PASSWORD_MERCHANT = 'FORGOT_PASSWORD_MERCHANT';
export const FORGOT_PASSWORD_MERCHANT_SUCCESS = 'FORGOT_PASSWORD_MERCHANT_SUCCESS';
