export const GET_PAYMENT_USER = 'GET_PAYMENT_USER';
export const GET_PAYMENT_USER_SUCCESS = 'GET_PAYMENT_USER_SUCCESS';

export const GET_PAYMENT_DETAIL_USER = 'GET_PAYMENT_DETAIL_USER';
export const GET_PAYMENT_DETAIL_USER_SUCCESS = 'GET_PAYMENT_DETAIL_USER_SUCCESS';

export const GET_PAYMENTS_MERCHANT = 'GET_PAYMENTS_MERCHANT';
export const GET_PAYMENTS_MERCHANT_SUCCESS = 'GET_PAYMENTS_MERCHANT_SUCCESS';

export const GET_PAYMENT_DETAIL_MERCHANT = 'GET_PAYMENT_DETAIL_MERCHANT';
export const GET_PAYMENT_DETAIL_MERCHANT_SUCCESS = 'GET_PAYMENT_DETAIL_MERCHANT_SUCCESS';
