export const UPDATE_FORGOT_PASSWORD_USER = 'UPDATE_FORGOT_PASSWORD_USER';
export const UPDATE_FORGOT_PASSWORD_USER_SUCCESS = 'UPDATE_FORGOT_PASSWORD_USER_SUCCESS';

export const UPDATE_FORGOT_PASSWORD_MERCHANT = 'UPDATE_FORGOT_PASSWORD_MERCHANT';
export const UPDATE_FORGOT_PASSWORD_MERCHANT_SUCCESS = 'UPDATE_FORGOT_PASSWORD_MERCHANT_SUCCESS';
